### ISSUE TITLE
Why you use such huge epsilon for adam, what is the philosophy behind

### ISSUE THREAD

**Issue by menglin0320** [timsainb/Tensorflow-MultiGPU-VAE-GAN#2]
And you use elu as the activation function, is this activation function guaranteed to be better than relu for this task?

**Comment by timsainb** [comment]
No philosophy behind any of this, it's just a kind of starting point if anybody wants to try to experiment around. I believe that I found that the large epsilon learned a little faster, and I think that the reason I tried it was because of ikostrikov's implementation (which has since changed significantly): https://github.com/ikostrikov/TensorFlow-VAE-GAN-DRAW
